### ISSUE TITLE
When uploading file - curl: (3) <url> malformed

### ISSUE THREAD

**Issue by xnosek00** [labbots/google-drive-upload#10]
Hi, 
 there is a bug in your script. Fresh download of script - today.
 I use script this way: ./upload.sh vojtkovi.xlsx -r folderID
 After Client ID and Client Secret and go to google.com/device and accepting, I have this message: 
`curl: (3) <url> malformed`

 I tested another account and it works good (the same procedure). But using another account is not solution. 

 log report: 

> ./upload.sh -v test.xlsx -r 0B6DPXMkEIRISN1RRaTJ6NGtUa21
> Folder ID for folder name  : 0B6DPXMkEIRISN1RRaTJ6NGtUa21
> Generating upload link for file vojtkovi.xlsx ...
> Uploading file test.xlsx to google drive...
> curl: (3) <url> malformed

**Comment by xnosek00** [comment]
this example is without folder (using root folder) with the same result. File size is 600kB and I have free 3GB of disk space on google drive.
>./upload.sh -v test.xlsx 
>Folder ID for folder name  : root
>Generating upload link for file test.xlsx ...
>Uploading file test.xlsx to google drive...
>curl: (3) <url> malformed

**Comment by mgbarton** [comment]
If you tweak the upload.sh script to show the data being returned by curl in the uploadlink step, you will probably see that the curl command is returning an error.  In my case, it provided a URL for the  the developers console, where I had to enable the Google Drive API for my account.

**Comment by xnosek00** [comment]
Hi, you're right. My Google Drive API for that account was disabled. 
This link helps me to enable it: https://console.developers.google.com/apis/library/drive.googleapis.com/?q=google%20driv

My fault. 
Thank you for help. You can close this issue. It works :)
