### ISSUE TITLE
Support for global installation

### ISSUE THREAD

**Issue by VictorBaudot** [labbots/google-drive-upload#103]
I'm creating a cronjob to upload some files every day to google drive. I can execute `gupload` when I'm logged in on my ubuntu vps but the cron can't find this command. How to make it accessible by all users on the server?

**Comment by Akianonymus** [comment]
@VictorBaudot I am actually working on global installation, will have to wait sometime.

Btw, you can use gsync to do sync jobs. Read synchronisation section of readme.

**Comment by VictorBaudot** [comment]
@Akianonymus ok, I will wait. `gsync` duplicates my files

**Comment by Akianonymus** [comment]
@VictorBaudot Read about -a | --arguments flag in synchronisation section in [README](https://github.com/labbots/google-drive-upload#synchronisation).

You can configure the gupload arguments there.

**Comment by VictorBaudot** [comment]
I yes, I missed the `-a` flag, thank you

**Comment by Akianonymus** [comment]
Fixed in latest release
