### ISSUE TITLE
How to remove existing files using script

### ISSUE THREAD

**Issue by testaccountsnt** [labbots/google-drive-upload#104]
This is an excellent script to take backups on google drive and it is very user friendly to integrate with Linux Machines.

Can we use it to remove older files from google drive? We have limited storage google drive and it gets full with in 20-22 days. If we forget removing manually, it does not store new backups.

Please help to run the utility for removing older files.

Thank You

**Comment by labbots** [comment]
The feature you requested is out of scope of this script. The use case for the script is for uploading file to Google drive. Deleting stale files is user specific preference as it could be based on multiple factors such as creation date, file name, folder name, size of file etc. So at present we would not consider implementing such feature. If this issue gets enough traction from other users then we might consider implementing it in future.
