### ISSUE TITLE
MimeType Error

### ISSUE THREAD

**Issue by capriciousduck** [labbots/google-drive-upload#105]
I get the following error while installing the script:

`"file or mimetype", not found, install before proceeding.`

**Comment by Akianonymus** [comment]
Just do what the message says, install file or mimetype command

**Comment by capriciousduck** [comment]
Oops! 

Fixed.

**Comment by Beomi** [comment]
for later visitors, on ubuntu, try this:

```bash
apt update && apt install -y file
```
