### ISSUE TITLE
Binary File

### ISSUE THREAD

**Issue by capriciousduck** [labbots/google-drive-upload#109]
Can you provide me a binary file? I just upload files to drive and I don't use other functions like sync.

**Comment by labbots** [comment]
What exactly do you mean by binary file @capriciousduck

**Comment by capriciousduck** [comment]
I mean a executable file. Something similar to this....

https://www.google.com/amp/s/olivermarshall.net/how-to-upload-a-file-to-google-drive-from-the-command-line/amp/

**Comment by Akianonymus** [comment]
Will push soon, just been busy..

**Comment by Akianonymus** [comment]
For bash - https://github.com/labbots/google-drive-upload/tree/master/bash/release

For sh - https://github.com/labbots/google-drive-upload/tree/master/sh
