### ISSUE TITLE
uploading files to team drive directory support

### ISSUE THREAD

**Issue by yahanvesh** [labbots/google-drive-upload#11]
I tried to upload a file to a team directory folder and it gave success but I couldnt find the file in the team drive.

Go to https://www.google.com/device and enter WYHS-KZZP to grant access to this application. Hit enter when done...
Folder ID for folder name  : 0AKvfXElmasdadasd
Generating upload link for file  abcfile.pdf ...

Uploading file .abcfile.pdf to google drive...
######################################################################## 100.0%

**Comment by labbots** [comment]
@yahanvesh I dont have a team drive to test this behaviour. So my guess would be to check the permissions for the access token.

**Comment by ArnoutVerbeken** [comment]
Change line 184 of upload.sh to
`"https://www.googleapis.com/upload/drive/v2/files?uploadType=resumable&supportsAllDrives=true" \
`

**Comment by shakerlxxv** [comment]
I can't say which would be be better but I initially tried adding `supportsTeamDrives=true&` to the uploadlink url (line 184) and it worked. I tried again with `supportsAllDrives=true&` and that also appears to work.

I would propose adding a command line option `-t | --team-drives` or perhaps `-a | --all-drives` to insert this URL parameter. Unless you'd like to test the All Drives option in your personal drive to see if it causes any issue. If not, the perhaps you'd prefer to just include this parameter always.

**Comment by labbots** [comment]
I believe this option is now available in the script based on PR from @frankent.
