### ISSUE TITLE
Cannot Sign in due to google disable

### ISSUE THREAD

**Issue by AArchLichKing** [labbots/google-drive-upload#111]
I followed the instruction closely but get the following output in terminal:
![image](https://user-images.githubusercontent.com/50974944/94421044-924b8d80-01b7-11eb-93f5-dd9ed049bc6a.png)

While click the url, I got this:
![image](https://user-images.githubusercontent.com/50974944/94420902-60d2c200-01b7-11eb-8e8a-d03ef6532d25.png)

**Comment by labbots** [comment]
@AArchLichKing Is it a personal gmail account or a corporate account?

**Comment by Akianonymus** [comment]
It's a problem with your client id and secret, generate new credentials.

**Comment by Akianonymus** [comment]
It's a problem with your client id and secret, generate new credentials.

> I followed the instruction closely but get the following output in terminal:
> ![image](https://user-images.githubusercontent.com/50974944/94421044-924b8d80-01b7-11eb-93f5-dd9ed049bc6a.png)
> 
> While click the url, I got this:
> ![image](https://user-images.githubusercontent.com/50974944/94420902-60d2c200-01b7-11eb-8e8a-d03ef6532d25.png)

You should generate new credentials, this happens if the a particular client id and secret is used more than 100 times ( I don't exactly remember the no of time ), this should be fixed by generating new credentials.

**Comment by AArchLichKing** [comment]
It is private EDU account.

**Comment by AArchLichKing** [comment]
Problem solved by generating new id! With many thanks! Closed the issues.
