### ISSUE TITLE
curl: (6) Couldn't resolve host 'HTTP'

### ISSUE THREAD

**Issue by lfernandorios** [labbots/google-drive-upload#114]
gupload -V -o inventario_web.csv
/root/.google-drive-upload/bin/gupload: línea 1591: printf: `(': carácter de formato inválido
[ Starting script ]
[ Workspace Folder:  ]
[  16vT3kwo92JE7qYdWpko  ]

[ Given Input: FILE ]
[ Upload Method: Overwrite ]

[ inventario_web.csv | 2.71 KB ]
[ Uploading.. ]

curl: (6) Couldn't resolve host 'HTTP'
[ Upload ERROR, inventario_web.csv not Uploaded. ]

/root/.google-drive-upload/bin/gupload: línea 1612: printf: `(': carácter de formato inválido
[  Time Elapsed: 0 minute(s) and 0 seconds  ]

**Comment by Akianonymus** [comment]
Make sure you are on latest release, just update if not using `gupload --update`

If the problem still persists, then do the following steps.

Run gupload --info and send output.

Also, run gupload -D /home/user/folder 2>| log 1>&2

send log file contents or just the file

**Comment by Akianonymus** [comment]
Reopen if issue persists. Closed due to inactivity and no information about the issue.
