### ISSUE TITLE
getting a 408 request timeout when trying to upload a zip file.

### ISSUE THREAD

**Issue by xaviercshp** [labbots/google-drive-upload#116]
using gupload archive.zip -r <folder_id>

it shows progress 100.00% then hangs an eventually I get the 408 timeout error html.

**Comment by xaviercshp** [comment]
well look at that I answered my own question. looks like this can be caused by having special characters in the file name so better to use -f flag to define the filename.

**Comment by Akianonymus** [comment]
Good to hear, btw what was the filename ?
