### ISSUE TITLE
Failed Files

### ISSUE THREAD

**Issue by capriciousduck** [labbots/google-drive-upload#121]
I got that some files failed to upload when I've put a folder upload. How do I know which files didn't upload?

`[ Total Files Uploaded: 765 ]
[ Total Files Failed: 3 ]

[  Time Elapsed: 30 minute(s) and 20 seconds  ]`

**Comment by Akianonymus** [comment]
Created a pr for this issue.

https://github.com/labbots/google-drive-upload/pull/129

**Comment by Akianonymus** [comment]
```
If upload failed for some files then

      If running in terminal, then

          if failed files > 20, then

            print to terminal

          else

            save to a log file, with a random name
```

      If not running in a terminal, then

          print all

**Comment by Akianonymus** [comment]
New release created with bug fix

https://github.com/labbots/google-drive-upload/releases/tag/v3.4.7
