### ISSUE TITLE
Install gupload

### ISSUE THREAD

**Issue by Roei639** [labbots/google-drive-upload#128]
Hello, I'm getting an installation error:
Cannot validate existing installation, make sure no other program is installed as gupload.
You can use -c / --cmd flag to specify custom command name.

Create a issue on github with proper log if above mentioned suggestion doesn't work.

**Comment by Akianonymus** [comment]
@Roei639 Do following commands and give log.

```
curl --compressed -Ls https://github.com/labbots/google-drive-upload/raw/master/install.sh | sh -s -- -D 2>| log 1>&2

```

Send `log` file here.

**Comment by Roei639** [comment]
I ran the command.  Does not accept error nor log

**Comment by Akianonymus** [comment]
@Roei639 It works fine here. I will need the log file to know the issue.

**Comment by Roei639** [comment]
+ return 0                                                                      
+ [ -n  ]                                                                       
+ _check_internet                                                               
+ _print_center justify Checking Internet Connection.. -                        
+ [ 3 = 3 ]                                                                     
+ printf %s\n Checking Internet Connection..                                    
Checking Internet Connection..                                                  
+ _timeout 10 curl -Is google.com --compressed                                  
+ timeout_timeout=10                                                            
+ shift                                                                         
+ _clear_line 1                                                                 
+ :                                                                             
+ _check_existing_command                                                       
+ command -v gupload                                                            
+ COMMAND_PATH=/home/roei/.local/bin/gupload                                    
+ [ -f /home/roei/.google-drive-upload/google-drive-upload.info ]               
+ grep -E ^VALUES_LIST=".*".* # added values|^REPO=".*".* # added values|^COMMA>
+ :                                                                             
+ SCRIPT_VALUES=                                                                
+ eval                                                                          
+ [ -n  ]                                                                       
+ printf %s\n Error: Cannot validate existing installation, make sure no other >
Error: Cannot validate existing installation, make sure no other program is ins>
+ printf %s\n\n You can use -c / --cmd flag to specify custom command name.     
You can use -c / --cmd flag to specify custom command name.                     
                                                                                
+ printf %s\n\n Create a issue on github with proper log if above mentioned sug>
Create a issue on github with proper log if above mentioned suggestion doesn't >
                                                                                
+ exit 1

**Comment by Akianonymus** [comment]
@Roei639 try removing `/home/roei/.local/bin/gupload` and try again.

**Comment by Roei639** [comment]
I deleted, showing the same error

Command gupload  - - version returns version 1.1.0

And the installation path files are not found.

**Comment by Akianonymus** [comment]
@Roei639 Reload terminal before trying again.

and send logs.

**Comment by Roei639** [comment]
```
+ return 0                                                                      
+ [ -n  ]                                                                       
+ _check_internet                                                               
+ _print_center justify Checking Internet Connection.. -                        
+ [ 3 = 3 ]                                                                     
+ printf %s\n Checking Internet Connection..                                    
Checking Internet Connection..                                                  
+ _timeout 10 curl -Is google.com --compressed                                  
+ timeout_timeout=10                                                            
+ shift                                                                         
+ _clear_line 1                                                                 
+ :                                                                             
+ _check_existing_command                                                       
+ command -v gupload                                                            
+ COMMAND_PATH=/usr/local/bin/gupload                                           
+ [ -f /home/roei/.google-drive-upload/google-drive-upload.info ]               
+ grep -E ^VALUES_LIST=".*".* # added values|^REPO=".*".* # added values|^COMMA>
+ :                                                                             
+ SCRIPT_VALUES=                                                                
+ eval                                                                          
+ [ -n  ]                                                                       
+ printf %s\n Error: Cannot validate existing installation, make sure no other >
Error: Cannot validate existing installation, make sure no other program is ins>
+ printf %s\n\n You can use -c / --cmd flag to specify custom command name.     
You can use -c / --cmd flag to specify custom command name.                     
                                                                                
+ printf %s\n\n Create a issue on github with proper log if above mentioned sug>
Create a issue on github with proper log if above mentioned suggestion doesn't >
                                                                                
+ exit 1
```

**Comment by Akianonymus** [comment]
@Roei639 Looks like you have it installed at a different place too.

remove /usr/local/bin/gupload and try again, in case of errors, give log.

**Comment by Roei639** [comment]
Installation successful.  Works thank you very much
