### ISSUE TITLE
Can't find the running job

### ISSUE THREAD

**Issue by VictorBaudot** [labbots/google-drive-upload#130]
I wonder why it says that the job is running, but typing "jobs" say the opposite 🤔
![image](https://user-images.githubusercontent.com/33088396/99672069-7cff2b00-2aa5-11eb-8d69-018fad8c1046.png)

**Comment by Akianonymus** [comment]
@VictorBaudot Use ps -p

jobs command only works for processes started in the same shell

**Comment by Akianonymus** [comment]
Closing as no response. If issue persists, reopen.
