### ISSUE TITLE
Not working on cron

### ISSUE THREAD

**Issue by george-dilthey** [labbots/google-drive-upload#132]
Heya! Love this thing! It works great when I run it directly in the command line, but if I schedule it via chron, it doesn't seem to work. Any ideas why?

Thanks!

**Comment by sabrio** [comment]
@george-dilthey did you found anything related to the above, I am having issue while trying to upload a file on google drive with cron job?

**Comment by george-dilthey** [comment]
I think what I ended up doing is rolling it into a shell script and running the shell script via cron.
