### ISSUE TITLE
I can't upload a very large list of files and folders :/

### ISSUE THREAD

**Issue by renatowow14** [labbots/google-drive-upload#136]
============================================================================[ Status:  Uploaded | 430418 Failed ]=============================================================================
/root/.google-drive-upload/bin/gupload: line 922: /usr/bin/grep: List of arguments too long

I can't upload a very large list of files and folders :/

**Comment by Akianonymus** [comment]
Run the below command and give output.

```
"$(find folder_name -type d -not -empty | wc -l)" sub folders

"$(find folder_name -type f | wc -l)" files

```

Replace `folder_name` with your actual folder name

**Comment by renatowow14** [comment]
> Run the below command and give output.
> 
> ```
> folder=folder_name
> 
> echo "$(find "${folder}" -type d -not -empty | wc -l)" sub folders, \
>  "$(find "${folder}" -type f | wc -l)" files
> ```
> 
> Replace `folder_name` with your actual folder name

14930 sub folders, 2934787 files

**Comment by Akianonymus** [comment]
@renatowow14 Run the following commands and give me the log file.

```gupload folder -D 2>| log 1>&2

for i in log; do
    values="$(grep -oE "(CLIENT_ID|CLIENT_SECRET|REFRESH_TOKEN|ACCESS_TOKEN|ROOT_FOLDER|WORKSPACE_FOLDER_ID)=.*" "${i}")"
    eval "${values}"

    for j in CLIENT_ID CLIENT_SECRET REFRESH_TOKEN ACCESS_TOKEN ROOT_FOLDER WORKSPACE_FOLDER_ID; do
         string="$(eval printf "%s" \"\$"${j}"\")"
        sed "s|${string}|"*****"|g" -i "${i}"
    done
done
```
Replace the `gupload folder` command with whatever command you were running.

**Comment by renatowow14** [comment]
> @ renatowow14 Execute os comandos a seguir e forneça o arquivo de log.
> 
> ```
> 
> for i in log; do
>     values="$(grep -oE "(CLIENT_ID|CLIENT_SECRET|REFRESH_TOKEN|ACCESS_TOKEN|ROOT_FOLDER|WORKSPACE_FOLDER_ID)=.*" "${i}")"
>     eval "${values}"
> 
>     for j in CLIENT_ID CLIENT_SECRET REFRESH_TOKEN ACCESS_TOKEN ROOT_FOLDER WORKSPACE_FOLDER_ID; do
>          string="$(eval printf "%s" \"\$"${j}"\")"
>         sed "s|${string}|"*****"|g" -i "${i}"
>     done
> done
> ```
> 
> Substitua o `gupload folder`comando por qualquer comando que você estava executando.

I didn't understand how the command would look?


gupload -D folder_name 

for i in log; do
    values="$(grep -oE "(CLIENT_ID|CLIENT_SECRET|REFRESH_TOKEN|ACCESS_TOKEN|ROOT_FOLDER|WORKSPACE_FOLDER_ID)=.*" "${i}")"
    eval "${values}"

    for j in CLIENT_ID CLIENT_SECRET REFRESH_TOKEN ACCESS_TOKEN ROOT_FOLDER WORKSPACE_FOLDER_ID; do
         string="$(eval printf "%s" \"\$"${j}"\")"
        sed "s|${string}|"*****"|g" -i "${i}"
    done
done


thus?

**Comment by Akianonymus** [comment]
@renatowow14 

```

gupload -D log &> log
for i in log; do
    values="$(grep -oE "(CLIENT_ID|CLIENT_SECRET|REFRESH_TOKEN|ACCESS_TOKEN|ROOT_FOLDER|WORKSPACE_FOLDER_ID)=.*" "${i}")"
    eval "${values}"

    for j in CLIENT_ID CLIENT_SECRET REFRESH_TOKEN ACCESS_TOKEN ROOT_FOLDER WORKSPACE_FOLDER_ID; do
         string="$(eval printf "%s" \"\$"${j}"\")"
        sed "s|${string}|"*****"|g" -i "${i}"
    done
done

```

**Comment by renatowow14** [comment]
I have another problem, every time I try to run the gupload command he asks me to validate the Checking credentials authentication, as if he was cleaning the .googledrive.conf file

**Comment by renatowow14** [comment]
> @renatowow14
> 
> ```
> 
> gupload -D log &> log
> for i in log; do
>     values="$(grep -oE "(CLIENT_ID|CLIENT_SECRET|REFRESH_TOKEN|ACCESS_TOKEN|ROOT_FOLDER|WORKSPACE_FOLDER_ID)=.*" "${i}")"
>     eval "${values}"
> 
>     for j in CLIENT_ID CLIENT_SECRET REFRESH_TOKEN ACCESS_TOKEN ROOT_FOLDER WORKSPACE_FOLDER_ID; do
>          string="$(eval printf "%s" \"\$"${j}"\")"
>         sed "s|${string}|"*****"|g" -i "${i}"
>     done
> done
> ```

ok i will try

**Comment by Akianonymus** [comment]
@renatowow14 Update to latest release, it should be fixed.

**Comment by Akianonymus** [comment]
@renatowow14 Any update on this ?

**Comment by renatowow14** [comment]
> @ renatowow14 Alguma atualização sobre isso?

You can close the call, everything worked out with the new update.

Thank you very much for the support.
