### ISSUE TITLE
Need to reinsert my credentials every 7 days.

### ISSUE THREAD

**Issue by jniquet-intelcom** [labbots/google-drive-upload#140]
Hello,
I'm having an issue with my credentials. I'm using gupload once every day on a cron. Every 7 days it seems I need to reinsert my credential in gupload (using the same oauth client ID, I just need to remove my config file and reinsert the details).

```Jan 16 00:05:01 honeypot2 CROND[3786977]: (jon) CMD (/home/jon/code/backupScript.sh)
Jan 16 00:05:07 honeypot2 CROND[3786961]: (jon) CMDOUT ([ Error: Something went wrong, printing error. ])
Jan 16 00:05:07 honeypot2 CROND[3786961]: (jon) CMDOUT ({)
Jan 16 00:05:07 honeypot2 CROND[3786961]: (jon) CMDOUT (  "error": "invalid_grant",)
Jan 16 00:05:07 honeypot2 CROND[3786961]: (jon) CMDOUT (  "error_description": "Token has been expired or revoked.")
Jan 16 00:05:07 honeypot2 CROND[3786961]: (jon) CMDOUT (})
Jan 16 00:05:07 honeypot2 CROND[3786961]: (jon) CMDOUT ([ [ Error: Credentials checking failed ] ])
```

I'm not super knowledgeable of google api, is it something expected? Is the refresh of my token not working? 

```[USER@MACHINE log]$ gupload --info
REPO: "labbots/google-drive-upload"
INSTALL_PATH: "/home/USER/.google-drive-upload/bin"
INSTALLATION: "bash"
TYPE: "release"
TYPE_VALUE: "latest"
LATEST_INSTALLED_SHA: "28cd628c13cb25955bcde24ca7d529bed27164a2"
CONFIG: "/home/jon/.googledrive.conf"
```

`CentOS Linux release 8.3.2011`

**Comment by Akianonymus** [comment]
This is definitely weird, doesn't happens me, i am using it since a year now.

**Comment by jniquet-intelcom** [comment]
> This is definitely weird, doesn't happens to me, i am using it since a year now.

I've tried to generate a brand new oauth creds and see if it stays alive. Thanks for the reply, at least I know i'm an odd case!:)

**Comment by Akianonymus** [comment]
@jniquet-intelcom The thing which is more weird that it would happen after 7 days, i don't remember adding anything in the script specific to 7 days.

**Comment by shdobxr** [comment]
I had the same problem gents, I have some friends of mine that work at google, so I asked them... is there some sort of hard limit? One of my buddies pinged me this.

https://developers.google.com/identity/protocols/oauth2

Using this sort of auth, and honestly making sure some error handling is in there for refresh, is really what this is called for. My thought is that this is something that needs to be baked into the code so that if a "invalid grant" is returned, then a refresh of the token is performed. I fixed this by "regeneration" of client_ID and secret. Tho, I don't think this is necessary, but I can tell you that worked.

I think that there should be a way to tell the google API that hey my client and secret are valid... send me another refresh token or access token. Something there needs to be rehydrated.

**Comment by jkaan** [comment]
Perhaps this helps, but I'm using the same client ID and client secret for two instances of `gupload`, one of them hasn't been invalidated yet for 3 months, the other expires every week.

**Comment by jniquet-intelcom** [comment]
I've not had success since my initial reset of the credentials, it still reset (although initially i said 7 days, it actually is 8 days).
Trying a new set a credentials yet again.

Is it possible its related to the fact that I create my refresh token on my PC but for my server? (I don't really have ways to generate the refresh token on my server, at least not easily).

**Comment by jniquet-intelcom** [comment]
I've actually tried to setup google api access directly and am suffering from the same problem so I don't believe it's related to these scripts. Will close this issue and continue investigating on my side. I believe it's related to the fact that i generate my refresh token on my workstation but use the script on my server (without Desktop environment or webbrowser to generate the token).

**Comment by Synertry** [comment]
I had the same symptoms for a month now and even created a [personal sync frame for uploading and deploying the refresh token.](https://gist.github.com/Synertry/3baa660b39e6f3b53f9a33a7ae140490)
Manual deletion of the expired refresh token line in _.googledrive.conf_ and creation is still needed.

For anyone still searching for the source of the problem:
[https://developers.google.com/identity/protocols/oauth2#expiration](https://developers.google.com/identity/protocols/oauth2#expiration) states 
> A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

A solution would be to publish your custom application from the Google Cloud Platform:
[https://console.cloud.google.com/apis/credentials/consent](https://console.cloud.google.com/apis/credentials/consent)

**Comment by jniquet-intelcom** [comment]
Indeed, cleaning up my scopes and publishing my app seems to have resolved the problems I had.
Thank you @Synertry !
