### ISSUE TITLE
cannot specify google folder

### ISSUE THREAD

**Issue by santsang** [labbots/google-drive-upload#144]
I use -d to specify the folder.  The file only upload to the root of my google drive. May you give an example? Thanks.

**Comment by Akianonymus** [comment]
You are supposed to use -r / --rootdir flag, not -d / --skip-duplicates flag.

**Comment by santsang** [comment]
I got this impression from your homepage.  I have not tried -r yet.  I find that -c work too.  I do not know the difference between -r and -c.  Any suggestion?

**Comment by santsang** [comment]
A question (not criticism): Any plan in developing your app into something like this: https://github.com/andreafabrizi/Dropbox-Uploader.  I bet with google drive, it is not that easy.  However, given that you allow downloading things from google drive, it is perfectly possible. it will be nice if we can browser the content and delete files of google drive.

**Comment by Akianonymus** [comment]
@santsang -r flag uses folder id whereas -c flag uses folder name.

which homepage you are talking about again ?

**Comment by Akianonymus** [comment]
@santsang About developing into something like the dropbox uploader, yes, it's totally possible, as long as it can be done using api.

It's on my todo list, but cannot promise when i am gonna do it.

Also, given i maintain a posix version and parallel uploading, it takes even more time to implement a feature.

So, basically in a nutshell i am saying, i currently don't have time to do it, atleast till the next month. After that, i will definitely try.

**Comment by santsang** [comment]
> @santsang -r flag uses folder id whereas -c flag uses folder name.
> 
> which homepage you are talking about again ?

Many thanks for taking my question in a good way.  Here is the webpage: https://github.com/labbots/google-drive-upload.

It mentions:... gsync folder_name -d gdrive_folder...

I thought I simply replace gsync with gupload.  I use portable git....  I could not get gsync working.

I agree with you.  It is easy to suggest how people improve their app, but it is difficult to do so.  That is precisely I restrict my computational skills to analytical levels ;).

Thanks for the hard work.  I was so happy to find app.  I do not need to install any other app.  One more app means more chance for messing up a system.

**Comment by Akianonymus** [comment]
You are mixing gsync and gupload, please read the readme more carefully.

**Comment by santsang** [comment]
> 
> 
> You are mixing gsync and gupload, please read the readme more carefully.

Yes, I understand.  I could not get gsync working on my machine.  Since gupload works, it just uses it to save study time:).  Many thanks again.

**Comment by Akianonymus** [comment]
@santsang ooh, you meant gsync was not working. My bad, can you provide the logs, thank you.

**Comment by Akianonymus** [comment]
Reopen if issue persists. Closed due to inactivity and no information about the issue.
