### ISSUE TITLE
[ FEATURE ] Support for sub-folders with --create-dir flag.

### ISSUE THREAD

**Issue by rdelgadou** [labbots/google-drive-upload#155]
I am trying to use gupload to upload a bunch of files that are organized in folders like this:

1995/01/<several files>
1995/02/<several files>
...
1995/12/<several files>

In a folder on GDrive that should like this (from the GDrive root directory):
Moclim/20THC/1995/01
Moclim/20THC/1995/02
...
Moclim/20THC/1995/02

Moclim is the root folder for gupload (I configured it as so during initial setup).

I run:
`gupload 1995/01/* -c "./Moclim/20THC/1995/01"`

gupload manages to upload the files, but the files get stored in Google Drive as:
Moclim/01/<files>

I have tried several options but I still do not get what is wrong with my command. Can you point me out in the right direction?

**Comment by Akianonymus** [comment]
-c doesn't support sub folder structure right now, only single folder.

As for a workaround, make the folders beforehand on drive and then upload to the common folder.
