### ISSUE TITLE
[BUG] Skip duplicates not working on some filenames

### ISSUE THREAD

**Issue by divyam234** [labbots/google-drive-upload#156]
I have some files named   like   10-abc -abc xyz't abx  which are not counted as duplicates  when I run the upload process second time I am assuming some special chars in file names are causing this  in this case it is caused to do comma but If I remove this comma then it is  counted as duplicate.

**Comment by Akianonymus** [comment]
Provide the exact filenames.

**Comment by divyam234** [comment]
gupload  "10-abctest's.ipynb" -d

Running this is creating two files with same name  here extension can be any extension

**Comment by Akianonymus** [comment]
@divyam234 Update to the latest version, fixes have been merged.
