### ISSUE TITLE
can you add shared drive support too ?

### ISSUE THREAD

**Issue by telegrambotdev** [labbots/google-drive-upload#157]
can you please add shared drive support too ?

**Comment by telegrambotdev** [comment]
This code is awsome. but there is no option for shared drive folder selection. can you please add that too ?

**Comment by Akianonymus** [comment]
Just create a folder in shared drive, use folder id like you would normally do.

Make sure you have access to it, should work.

**Comment by telegrambotdev** [comment]
> Just create a folder in shared drive, use folder id like you would normally do.
> 
> Make sure you have access to it, should work.

let me check
