### ISSUE TITLE
curl: (3) <url> malformed - empty curl string

### ISSUE THREAD

**Issue by okobloko** [labbots/google-drive-upload#16]
The ClientID/Secret/Root are setup but I'm getting a "curl: (3) <url> malformed" error.
I added a bit more logging to the relevant line -
`log "Generating upload link for file $FILE ...ACCESS TOKEN [${ACCESS_TOKEN}] MIME TYPE [$MIME_TYPE] FILE SIZE [$FILESIZE] postData [$postData]"`
All the variables are populated, but after setting the uploadlink variable, I can see that it is an empty string, resulting in the error.

Any ideas? I'm not sure what data to supply given that most of it is "private"?

**Comment by okobloko** [comment]
I've also just noticed that using the -C option to create a folder returns no error, but also fails to create any new folders.

**Comment by TariqKotwal** [comment]
Please check your client type while generating client id, it should be "other"

**Comment by Audio** [comment]
In my case there was a problem with root folder id. Validation requires folder id of length 28 characters, although drive.google,com shows pattern `<28 chars>-<4 chars>` in URL. If 28 chars folder id is used, Google API returns error 404 and `uploadlink` is empty. If full folder id is used, the script works just fine.

**Comment by Akianonymus** [comment]
Invalid Issue.
