### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by capriciousduck** [labbots/google-drive-upload#160]
I am getting the following error 

`--------------------------------------------------------[ Checking credentials.. ]----------------------------------------------------------
========================================================== All available accounts. ==========================================================
1. default1 
2. default 

========================================== Above accounts are configured, but default one not set. ==========================================
/root/.google-drive-upload/bin/gupload: line 720:  : command not found`

**Comment by Akianonymus** [comment]
> I am getting the following error
> 
> `--------------------------------------------------------[ Checking credentials.. ]----------------------------------------------------------
> ========================================================== All available accounts. ==========================================================
> 
> 1. default1
> 2. default
> 
> ========================================== Above accounts are configured, but default one not set. ==========================================
> /root/.google-drive-upload/bin/gupload: line 720: : command not found`

Will be fixed after https://github.com/labbots/google-drive-upload/pull/159 is merged

**Comment by Akianonymus** [comment]
Fixed in latest [release](https://github.com/labbots/google-drive-upload/releases/tag/v4.1), update.
