### ISSUE TITLE
[BUG] Garbled file names

### ISSUE THREAD

**Issue by kirill-kalinin** [labbots/google-drive-upload#162]
Uploaded files are getting wrong names

Command example: 
`gupload --config test/myconfig.conf --overwrite --quiet -f test/SomefilenameTestUpload_123.45.apk -c 123.45_apk`

Uploaded file name:
`SomeilenameTes	Upload_123.45.apk`

**Comment by Akianonymus** [comment]
> --overwrite --quiet -f test/SomefilenameTestUpload_123.45.apk -c 123.45_apk

Are you on latest release ? Because it's working fine here

![image](https://user-images.githubusercontent.com/32216346/121513152-2557eb00-ca08-11eb-92fc-6f734d8910c8.png)

**Comment by kirill-kalinin** [comment]
Yes, it's the latest release, i had no this problem before last update. Terminal shows proper file name, but uploaded file real name is different.
<img width="1065" alt="Screenshot 2021-06-10 at 2 06 41 PM" src="https://user-images.githubusercontent.com/52810073/121515792-3f88cd80-c9f6-11eb-8666-efa6d1c6a184.png">

**Comment by Akianonymus** [comment]
Well, here it's perfectly fine.

![image](https://user-images.githubusercontent.com/32216346/121517918-833b0180-ca0d-11eb-8160-263152c687fb.png)

I will need debug logs to further investigate in the issue.

Run below command to grab the debug logs and remove sensitive information from the log

```
gupload --config test/myconfig.conf --overwrite --quiet -f test/SomefilenameTestUpload_123.45.apk -c 123.45_apk -D &> log

file=log
values="$(grep -oE "(CLIENT_ID|CLIENT_SECRET|REFRESH_TOKEN|ACCESS_TOKEN|ROOT_FOLDER|WORKSPACE_FOLDER_ID|uploadlink)=.*" "${file}" | sed "s/.*=//g" | sed -e "s/^[\"]\+//g" -e "s/[\"]\+$//g" -e "s/^[\']\+//g" -e "s/[\']\+$//g" &&
    grep -oE "\"id\"\:.*" "${file}" | sed -e "s/.*\"id\"://" -e 's/[",]*$//' -e 's/["]*$//' -e 's/[,]*$//' -e "s/^ //" -e 's/^"//')"

printf "%s\n" "${values}" | while read -r value; do
    sed "s|${value}|null|g" -i "${file}"
done
```

( This will use -D flag to show debug logs and &> to redirect all of it to file named log, further commands to remove senstive information )

**Comment by kirill-kalinin** [comment]
Here is it:
[log.txt](https://github.com/labbots/google-drive-upload/files/6631745/log.txt)

I should say i use Mac OS

**Comment by Akianonymus** [comment]
@kirill-kalinin Well, last statement made it clear, primitive mac os sed is messing up again.

Run below command and give output.

`echo "$(printf '\t')SomefilenameTestUpload_123.45.apk" | sed "s/$(printf '\t')/tt/"`

**Comment by Akianonymus** [comment]
@kirill-kalinin Well, last statement made it clear, primitive mac os sed is messing up again.

Run below command and give output.

`echo "$(printf '\t')SomefilenameTestUpload_123.45.apk" | sed "s/$(printf '\t')/tt/"`

**Comment by kirill-kalinin** [comment]
Output:
ttSomefilenameTestUpload_123.45.apk

**Comment by Akianonymus** [comment]
@kirill-kalinin So, i have got the fixes, will push asap.

Currently as a workaround, you can either use bash 4.x or update sed with gnu sed.

**Comment by Akianonymus** [comment]
@kirill-kalinin Execute below commands and try to upload again.

```
path="$(which gupload)" &&
    chmod +w "${path}" &&
        curl -sL https://github.com/Akianonymus/google-drive-upload/raw/wip/sh/release/gupload -o "${path}" &&
            echo "Success"
```

**Comment by Akianonymus** [comment]
Try the latest release, if not fixed, reopen the issue.
