### ISSUE TITLE
Cannot upload to Drive

### ISSUE THREAD

**Issue by rezaarifian** [labbots/google-drive-upload#165]
Hello, I'm getting problem an upload to drive:
my script run on file `.gitlab-ci.yml`
first the script working upload APK to drive.
a month ago this code not working on process is `success` but file APK not appear on Drive.

[
<img width="898" alt="Screen Shot 2021-06-15 at 16 16 18" src="https://user-images.githubusercontent.com/16816082/122028902-a8a58200-cdf6-11eb-99ef-b64b8861d0d5.png">
](url)

**Comment by Akianonymus** [comment]
> Hello, I'm getting problem an upload to drive:
> my script run on file `.gitlab-ci.yml`
> first the script working upload APK to drive.
> a month ago this code not working on process is `success` but file APK not appear on Drive.
> 
> [ <img alt="Screen Shot 2021-06-15 at 16 16 18" width="898" src="https://user-images.githubusercontent.com/16816082/122028902-a8a58200-cdf6-11eb-99ef-b64b8861d0d5.png"> ](url)

Try running the commands without a subshell, what it outputs, without the `

From the looks of it, not able to connect to the internet, which is weird.

**Comment by Akianonymus** [comment]
Reopen if needed.
