### ISSUE TITLE
Frozen when using gupload

### ISSUE THREAD

**Issue by KorewaLidesu** [labbots/google-drive-upload#166]
Is it normal that after upload, the script will just frozen for a few minutes?
Like this?
![image](https://user-images.githubusercontent.com/24401452/122077829-4795a280-ce26-11eb-9d29-d26fe90703a8.png)

```f1 = open('downloaded.txt', 'w' )
with open('batch.txt') as f:
  for line in f:
    !rm -rf $output/*
    !yt-dlp --embed-thumbnail --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 -ciw -o '$output/%(title)s.%(ext)s' $line
    !google-drive-upload/bash/release/gupload -a Drive -s youtube/*.mp4
    f1.writelines(line)```

**Comment by KorewaLidesu** [comment]
Huh, it just weird for me...

**Comment by Akianonymus** [comment]
@KorewaLidesu After script shows Time Elapsed, it means it exited.

**Comment by Akianonymus** [comment]
Also, can you tell this command output from where you are running

```
echo "${TERM}"
```
( not related to your bug )

**Comment by KorewaLidesu** [comment]
xterm-color

**Comment by KorewaLidesu** [comment]
> @KorewaLidesu After script shows Time Elapsed, it means it exited.

It just sometimes random stop right there. I need to trigger Interrupt command or it just stay there forever.

**Comment by KorewaLidesu** [comment]
> Also, can you tell this command output from where you are running
> 
> ```
> echo "${TERM}"
> ```
> 
> ( not related to your bug )

`xterm-color`
Using Google colab

> @KorewaLidesu After script shows Time Elapsed, it means it exited.

It just sometimes random stop right there. I need to trigger Interrupt command or it just stay there forever.
