### ISSUE TITLE
No valid arguments provided for root dir flag

### ISSUE THREAD

**Issue by Gnai** [labbots/google-drive-upload#175]
Hello! I couldn't set the root folder again with the `-r` flag 

```
gupload -r default={asfejhI9230rNLDCNaionareefff} 
No valid arguments provided, use -h/--help flag to see usage.
```

**Comment by Gnai** [comment]
Also getting this error : 
`gupload -r default={asfejhI9230rNLDCNaionareefff} 

No valid arguments provided, use -h/--help flag to see usage.`

**Comment by Gnai** [comment]
I was able to edit the config file using `sudo nano` and the folder ID and the name. 
Setting this up with -r flag was impossible. 
I was also wondering if that needs to be set up for someone who has no knowledge in coding, it would be a cumbersome process. Making it more straight-forward and an out-of-the box process to set up/connect the auth. to drive would be ideal. 
Thank you for this tool ! I am actually using it to upload files automatically with LUA. Which can't be done in Python from LUA ! 
Thanks again

**Comment by Akianonymus** [comment]
@Gnai Why are enclosing it in parentheses ?

**Comment by Gnai** [comment]
same error, I tried everything

**Comment by Akianonymus** [comment]
How did you install gupload ?

**Comment by Gnai** [comment]
with the command line using pip

**Comment by Akianonymus** [comment]
I don't gupload is on pip

Read this: https://labbots.github.io/google-drive-upload/setup/install/
