### ISSUE TITLE
gupload: line 724: 1: Give account name

### ISSUE THREAD

**Issue by borland502** [labbots/google-drive-upload#176]
```bash
12:15:28 ❯ gupload ~/.todo/todo.txt
[ Checking credentials.. ]
[  New account name:  ]
[ Info: Account names can only contain alphabets / numbers / dashes. ]

[  Given account name:   ]
/Users/foo/.google-drive-upload/bin/gupload: line 724: 1: Give account name

~  took 14s
🕙 12:26:14 ❯ gupload ~/.todo/todo.txt
[ Checking credentials.. ]
[  New account name:  ]
[ Info: Account names can only contain alphabets / numbers / dashes. ]
```

This is likely a usability (user error) bug, rather than a true bug given no issues submitted.  However, no matter what I type for the account name  `Test, default, [client-id]` the result is an exit before anything is setup with the error above.  No, I lie, if I do client_id I do get an invalid complaint.

zsh using iterm, macos: darwin20.0

update:  I got around the setup issue by using the -ca flag and things proceeded as I expected.  Thanks for the script, but I had little clue why one route worked and the default route failed.

**Comment by Akianonymus** [comment]
I will looks into it, probably some typo.
