### ISSUE TITLE
Resume recursive folder uploads

### ISSUE THREAD

**Issue by mdawart** [labbots/google-drive-upload#178]
I am not sure if this is the right way to ask: How can I achieve a resumable upload of a recursive folder upload? 

I have a folder with subfolders and files in it, some huge. I tried to simulate a connection issue by exiting the script manually and starting the command again. But against my assumption a new version of the folder was created besides the one created on an earlier upload, and in the `$HOME/.google-drive-upload/` folder there are entries for each try: 

```
-rw-r--r--   1 michael  staff   233 26 Okt 13:21 Untitled CAM 1.mp4__::__11eMWZ178D77WXw9-K2ruR-j7gG7XXXXX__::__15346761492
-rw-r--r--   1 michael  staff   233 26 Okt 13:17 Untitled CAM 1.mp4__::__1Pa14evlB2DzSEumzOCeZAPxx1I_XXXXX__::__1534676XXXX
-rw-r--r--   1 michael  staff   233 26 Okt 13:23 Untitled CAM 1.mp4__::__1cJxZdwUmjGXTMeljTyIpgYtp5IeXXXXX__::__1534676XXXX
-rw-r--r--   1 michael  staff   233 26 Okt 13:18 Untitled CAM 1.mp4__::__1fMN8t-wnw-67G_miGSyj7VAYrGuXXXXX__::__1534676XXXX
```

(Edit: Changed filename to hide ID?

I am using the command 

`gupload [local folder name]  -r [ID of the parent folder in Google Drive]`

**Comment by Akianonymus** [comment]
Normally, you shouldn't need to mess with anything else.

Does it not work by default ?

**Comment by mdawart** [comment]
Tried today with latest version, still the same behavior. Is there anything I can provide you to better understand the issue?
