### ISSUE TITLE
OAuth method deprecated

### ISSUE THREAD

**Issue by a14i3e20** [labbots/google-drive-upload#183]
Hello

I try to configure gupload for hours and i have an issue with the aujthorization code. Google return an error 400 invalid request _redirect_uri: urn:ietf:wg:oauth:2.0:oob_ . I found it's no more possible to connect to the google account via the OOB method since 28/02: https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#instructions-oob

Is there another way to get this code?

**Comment by xnosek00** [comment]
Hi, I can confirm the same problem. 

It is not possible to authorize appliaction du to "error 400 invalid request". So it is not possible to use this plugin for now. 

Accounts, which were authorized in past will work, but new instalations will not work.
