### ISSUE TITLE
File size limited on upload

### ISSUE THREAD

**Issue by Cub1tor** [labbots/google-drive-upload#184]
Trying to upload photos to the shared drive, everything works just fine except the fact, that only 4Kb of each file is uploaded, instead of full size

Command used:

```
gupload local_folder -r shared_folder_id
```

**Comment by Cub1tor** [comment]
MacOS is incredibly stupid, 4Kb copies with "._" before the name for EACH file
Idiots
My fault, sorry for useless Issue

**Comment by Akianonymus** [comment]
> MacOS is incredibly stupid, 4Kb copies with "._" before the name for EACH file Idiots My fault, sorry for useless Issue

Sorry but can you elaborate ? I didn't quite understand what was the issue.

**Comment by Cub1tor** [comment]
Sure
I wanted to upload the folder with photos and I've seen that each file uploaded is only 4Kb, instead of it's original size, so I stopped the upload and tried to figure out what was wrong.
After an hour I realized, that MacOS made a 4Kb file with something(I don't even know what for) for each photo in the folder.

Photo IMG_1.jpg -> 4Kb file named "._IMG_1.jpg"

![image](https://user-images.githubusercontent.com/22455000/168433146-6585af1f-197f-4cd7-b7a5-261b64f3c2b4.png)

I've removed all this junk and everything is ok now, sorry for posting stupid issue.

**Comment by Akianonymus** [comment]
oh, no worries. By the way, maybe those are thumbnails ?

**Comment by Cub1tor** [comment]
I thought about thumbnails, but aren't they supposed to be readable?

Found this:

> They're created to store file information that would otherwise go into an extended attribute on HFS+ (Apple native) or Unix/UFS volumes; in earlier Mac OS this would be the resource fork. Finder file operations will create them automatically to store the icon information, plus Time Machine stores some information in them so if you copy a file backed up via TM it will have that information copied as well.
