### ISSUE TITLE
Unable to authenticate (v4.4)

### ISSUE THREAD

**Issue by manzolo** [labbots/google-drive-upload#188]
I tried to run the gupload command, and after finishing the configuration I get the error
_**Error: Cannot fetch refresh token, make sure the authorization code was correct.**_

- gupload file.png 
---------------------------------[ Checking credentials.. ]-------------------------------------------------------------------
- ============================================================================ 
New account name:
 - ===========================================================================
Info: Account names can only contain alphabets / numbers / dashes.                                                                         

- ============================================================================
Given account name: [MYNAME]
- ============================================================================

------------------------------------------------------------------------------------------------- 
Enter Client ID
-------------------------------------------------------------------------------------------------
-> [MY_CLIENT_ID].apps.googleusercontent.com

----------------------------------------------------------------------------------------------- 
Enter Client SECRET 
-----------------------------------------------------------------------------------------------
-> [MY_CLIENT_SECRET]

If you have a refresh token generated, then type the token, else leave blank and press return key..                                                        

-------------------------------------------------------------------------------------------------- 
Refresh Token
 --------------------------------------------------------------------------------------------------
-> 
---------------------------------------------------------------------------- 
No Refresh token given, follow below steps to generate..
 -----------------------------------------------------------------------------

Visit the below URL, follow the instructions and then come back to commandline                                                                   

https://accounts.google.com/o/oauth2/auth?client_id=[MY_CLIENT_ID].apps.googleusercontent.com&redirect_uri=http%3A//localhost%3A8080&scope=https://www.googleapis.com/auth/drive&response_type=code&code_challenge_method=plain&code_challenge=99999999authorization_code
----------------------------------------------------------------------------- 
Press enter if you have completed the process in browser
-----------------------------------------------------------------------------

Error: Cannot fetch refresh token, make sure the authorization code was correct.

![immagine](https://user-images.githubusercontent.com/7722346/179501684-2455a430-f92d-42e6-b9c7-8bea4e964450.png)

**Comment by Akianonymus** [comment]
Will be fixed after the PR is merged.

**Comment by Roei639** [comment]
When trying to access the link, an error is received:

This site cannot be accessed

 Could not connect to localhost.

 You should try:

 check the connection

 ERR_CONNECTION_REFUSED

**Comment by Akianonymus** [comment]
@Roei639 You should create another issue with logs.

**Comment by manzolo** [comment]
> Will be fixed after the PR is merged. Until it is merged, can use this for now https://github.com/Akianonymus/google-drive-upload/raw/master/release/bash/gupload

It works perfectly
