### ISSUE TITLE
curl: (3) <url> malformed

### ISSUE THREAD

**Issue by nepohex** [labbots/google-drive-upload#19]
Hello! 
Thank you for your job! 

I was working with it almost month, uploaded more than 2TB to my Drive hundred times by 10GB files, but 2 days ago it become to throw an error.

`curl: (3) <url> malformed`

What I've already tried:
- Deleted config, reinstalled, re-autorize with current project in development console.
- Created new project in development console, done same in prev step.

Nothing worked for me. What to do? I see my requests in development console, errors.

**Comment by eduardomazolini** [comment]
Me too!

**Comment by eduardomazolini** [comment]
I permanently deleted items from my google drive and it worked.

**Comment by nepohex** [comment]
For me it started to work after 24+ hours. I think it's something like shadow ban in google Drive if you upload more than 1TB in 24 hours (thats what I did in that day).

**Comment by oamado** [comment]
I have the same issue? any update?

**Comment by Akianonymus** [comment]
Drive have a limit of 750 GB data upload for a day.

**Comment by labbots** [comment]
As @Akianonymus mentioned this is due to google drive upload limit for a day. Try the latest update which provides debug message to see the errors.
