### ISSUE TITLE
What scopes are needed?

### ISSUE THREAD

**Issue by marvic2409** [labbots/google-drive-upload#191]
I'm trying to use this script for a simple file upload to a folder in my personal google drive and when using the Oauth keys in testing, they get revoked every couple of days. In order to push the project to public, I need to know which scopes are needed. Which scopes does this script request for?

**Comment by marvic2409** [comment]
I changed the scope in the script from auth/drive to auth/drive.file and that allowed me to publish the oauth app without verification

**Comment by Akianonymus** [comment]
Hmm, interesting, i will probably make a change to the script then.
