### ISSUE TITLE
The whole file is being stored in memory

### ISSUE THREAD

**Issue by y3nd** [labbots/google-drive-upload#2]
Causing a curl error for big files :
`curl: option --data-binary: out of memory`

**Comment by labbots** [comment]
@y3nd could you please let me know the size of file you are trying to upload?

**Comment by y3nd** [comment]
Near 2 GB, the file has to be chunked for RAM optimization.

**Comment by dhiva** [comment]
I think that makes sense. If you have come up with an option to do the chunking please create a PR. I will also try working on it.

**Comment by R4to0** [comment]
On line 197:
https://github.com/labbots/google-drive-upload/blob/master/upload.sh#L197

Change 
`--data-binary "@$FILE" \`

to
`--upload-file "$FILE" \`

Worked for me, uploaded a 2,3GB file on a 1,5GB system with 700MB free RAM.

**Comment by labbots** [comment]
Updated that script. Thanks for your feedback @R4to0

**Comment by nbarrera** [comment]
I was using tag v1.0 as I thought that was the latest version, and this fix is not there...
it would be great to have a new tag with important fixes like this.
