### ISSUE TITLE
issue on checking credentials

### ISSUE THREAD

**Issue by moeinrahimi** [labbots/google-drive-upload#25]
mine was working just fine, then when trying to upload files, shell hung up on checking credentials phase, I updated the code from repo and removed config file and now it stuck on after i enter authorization code.
update: now it stuck in root configured.
```
root@vm9575616492:~/scripts/google-drive-upload# bash ./upload.sh -r 12t2ARImEQBIC-7JpgX_YEqZ6QrPXWKEQ /root/db/04-28-2020.tar.gz --debug
[ Starting script ]
[ Checking credentials... ]
If you have a refresh token generated, then type the token, else leave blank and press return key..
    Refresh Token:

Visit the below URL, tap on allow and then enter the code obtained:
https://accounts.google.com/o/oauth2/auth?client_id=2288823-j1ohpbqfnhds2liae5ob.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&scope=https://www.googleapis.com/auth/drive&response_type=code&prompt=consent
[ Root dir properly configured ]

```

**Comment by Akianonymus** [comment]
> mine was working just fine, then when trying to upload files, shell hung up on checking credentials phase, I updated the code from repo and removed config file and now it stuck on after i enter authorization code.
> update: now it stuck in root configured.
> 
> ```
> root@vm9575616492:~/scripts/google-drive-upload# bash ./upload.sh -r 12t2ARImEQBIC-7JpgX_YEqZ6QrPXWKEQ /root/db/04-28-2020.tar.gz --debug
> [ Starting script ]
> [ Checking credentials... ]
> If you have a refresh token generated, then type the token, else leave blank and press return key..
>     Refresh Token:
> 
> Visit the below URL, tap on allow and then enter the code obtained:
> https://accounts.google.com/o/oauth2/auth?client_id=2288823-j1ohpbqfnhds2liae5ob.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&scope=https://www.googleapis.com/auth/drive&response_type=code&prompt=consent
> [ Root dir properly configured ]
> ```

Try from my repo.

I will check soon..

https://github.com/Akianonymus/google-drive-upload

**Comment by Akianonymus** [comment]
@moeinrahimi I just tried a fresh setup, just pushed a fix for setting `root` as root folder.

Wait till my PR is merged or try using my repo 
https://github.com/Akianonymus/google-drive-upload

Cheers.

**Comment by labbots** [comment]
@moeinrahimi @Akianonymus The PR is now merged.
