### ISSUE TITLE
Running from jenkins

### ISSUE THREAD

**Issue by silviuvulcan** [labbots/google-drive-upload#27]
This is a weird one, hopefully you have an idea. But first, thank you for this ! it's very useful.

I'm running google-drive-upload from jenkins (to upload some artifacts) and the job fails (even though results are uploaded). Jenkins checks exit code and it seems to be "1"

````bash
[Pipeline] sh
[ Starting script ]
[ Checking credentials... ]
[1A[2K[1A[2K[ Required credentials available ]
[ Checking root dir and workspace folder.. ]
[1A[2K[1A[2K[ Root dir properly configured ]
[1A[2K[ Workspace Folder: TEST2 | FOLDER_ID ]
[ Time Elapsed: 0 minute(s) and 0 seconds ]
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
````

So I tried running with -D to see where it fails and with -D it works fine (with exit level 0) which makes me think it's something related to the background processing. Maybe a `--batch` mode could be helpful ?

**Comment by Akianonymus** [comment]
@silviuvulcan Can you try out this PR and report if issue exists??
https://github.com/labbots/google-drive-upload/pull/24

**Comment by silviuvulcan** [comment]
Sure, will test but probably only tomorrow.

By --batch I mean a mode that is batch processing friendly, i.e.:

- doesn't manipulate output like it now does (by writing status on the same line, background tasks, etc)
- doesn't have progress bars
- runs commands one by one, not in the background
- doesn't use special characters and/or colors

Basically something that is friendly to being run automatically and piping output to a text log.

**Comment by Akianonymus** [comment]
@silviuvulcan I have added commits in the same PR.

https://github.com/labbots/google-drive-upload/commit/5312bd07808e59d718f5104cafe6d69a5e41dbc8

Here is a sample log: https://del.dog/imamicidir.md

Suggest if you have any ideas to improve.

For saving output to a log, will try later to implement in a flag.

**Comment by labbots** [comment]
@silviuvulcan the code is now merged to master. Do you still have the issue?

**Comment by silviuvulcan** [comment]
sorry for the delay

I tried testing but it seems another bug crept in:

```bash
$ bash ./upload.sh --config /home/user/.gdrive-credentials -r 1SOME_ID -C TESTFOLDER
./upload.sh: --config: option requires an argument
Try ./upload.sh -h/--help for more information.
```

**Comment by Akianonymus** [comment]
@silviuvulcan Longoptions was broken, my bad :(

pushed a fix

https://github.com/labbots/google-drive-upload/commit/c360aec21caaea468b6b4d2a3ea577f35caab177

**Comment by labbots** [comment]
@Akianonymus could you please raise this fix as a separate PR

**Comment by Akianonymus** [comment]
@labbots Done 👍

**Comment by Akianonymus** [comment]
@labbots I think you should've waited for his confirmation unless and until you checked on jenkins

**Comment by labbots** [comment]
@silviuvulcan could you please confirm whether the fix worked for you

**Comment by silviuvulcan** [comment]
Did a quick check - both with and without --quiet is now working fine from jenkins. Also output in the jenkins log without "quiet" looks a lot better, the weird chars are gone:

```bash
[ Checking Internet connection.. ]
[ Starting script ]
[ Checking credentials.. ]
[ Required credentials available. ]
[ Checking root dir and workspace folder.. ]
[ Root dir properly configured. ]
[ Checking Workspace Folder.. ]
[ Workspace Folder: xxxxxx ]
[  FOLDER_ID ]

[ Given Input: FILE ]
[ Upload Method: Create ]

[ TESTFILE2 | 0.00 B ]
[ Generating upload link.. ]
[ Uploading.. ]

######################################################################## 100.0%
[ TESTFILE2 | 0.00 B | Uploaded ]
[ DriveLink ]
[ https://drive.google.com/open?id=xxxx ]

[  Time Elapsed: 0 minute(s) and 3 seconds  ]
```

Great job!

**Comment by labbots** [comment]
Perfect @silviuvulcan I am closing this ticket then.
