### ISSUE TITLE
Uploading Folders recursively

### ISSUE THREAD

**Issue by mspgalaxys2lite** [labbots/google-drive-upload#30]
There's a problem uploading folders recursively:
Let's say folder_to_upload has one folder namely folder_1 which has multiple folders namely folder_11, folder_12 and folder_13

The following command: ./upload.sh -r <google-folder-ID> path/folder_to_upload

creates a folder with the name folder_to_upload in the google drive folder with ID <google-folder-ID> but creates folders folder_12 and folder_13 in folder_11.

**Comment by Akianonymus** [comment]
https://github.com/labbots/google-drive-upload/commit/c96bc374556b38796c91b0ba2b8eb54e290877e3

Try and report :)

**Comment by mspgalaxys2lite** [comment]
I tried with new upload.sh file, now folder_1 is not created. folder_11,
folder_12 are available in folder_to_upload folder itself after upload.

**Comment by labbots** [comment]
@mspgalaxys2lite is that the expected behaviour you are looking for?

**Comment by Akianonymus** [comment]
@mspgalaxys2lite https://github.com/labbots/google-drive-upload/pull/29

try this

**Comment by mspgalaxys2lite** [comment]
That is not the expected behaviour.

folder_to_upload has folder_1.
folder_1 has folder_11, folder_12 and folder_13.

After Fix#30, I see folder_to_upload itself has folder_11, folder_12 and
folder_13. folder_1 is absent.

**Comment by labbots** [comment]
PR is now merged

**Comment by mspgalaxys2lite** [comment]
Fix #30 is not working.

**Comment by mspgalaxys2lite** [comment]
Still hierarchy is not maintained properly.

**Comment by Akianonymus** [comment]
ok, i agree, foolish of me to not test all possible scenarios, working on a fix now..

This has been a real pain  😂

**Comment by Akianonymus** [comment]
@mspgalaxys2lite 

Try this script
https://github.com/Akianonymus/google-drive-upload/blob/master/upload.sh

**Comment by Akianonymus** [comment]
@labbots Please reset to previous commit ( https://github.com/labbots/google-drive-upload/commit/1b0345d6ad69fa753d14f3d1e5128e8ca552c5e2 ).

Then, after confirmation from @mspgalaxys2lite , cherry pick my commit that i have force pushed ( https://github.com/Akianonymus/google-drive-upload/commit/b2f2f16cbdd18f89c2f685c49e2dd81928b3d681 ) and force push.

I don't wanna mess up the git history by making another PR.

**Comment by mspgalaxys2lite** [comment]
Not an issue mate.. you have created such a wonderful script.

**Comment by mspgalaxys2lite** [comment]
Looks like hierarchy is properly maintained now. Unable to test it properly
as I am repeatedly getting this: "curl: (6) Could not resolve host: HTTP".

**Comment by Akianonymus** [comment]
@mspgalaxys2lite can you tell me exact folder structure you have ?? thx

**Comment by labbots** [comment]
@Akianonymus I have reverted the commit and applied your commit from the fork. @mspgalaxys2lite could you please retest it.

**Comment by mspgalaxys2lite** [comment]
"folder_to_upload" has one folder inside it namely "folder_1".
"folder_1" has three folders in it namely "folder_11". "folder_12" and
"folder_13".

**Comment by Akianonymus** [comment]
@mspgalaxys2lite Tried my script ??

It works here..

**Comment by mspgalaxys2lite** [comment]
@Aki, its working now :-)
Thank you mate.

**Comment by labbots** [comment]
I am closing this ticket as it is now resolved. Thanks @Akianonymus for the fix and thanks @mspgalaxys2lite for testing it.

**Comment by Akianonymus** [comment]
@mspgalaxys2lite No problem.

btw, you tagged the wrong person, haha .
