### ISSUE TITLE
curl error

### ISSUE THREAD

**Issue by capriciousduck** [labbots/google-drive-upload#33]
I am getting the following error while trying to upload.

`curl: (6) Could not resolve host: HTTP`

**Comment by Akianonymus** [comment]
@capriciousduck Try running the script with -D flag and give logs

Also mention the exact command you used.

**Comment by Akianonymus** [comment]
This can be closed after #30 is fixed.

**Comment by labbots** [comment]
Closing the ticket as this is fixed as part of #30
