### ISSUE TITLE
Retry Failed Uploads

### ISSUE THREAD

**Issue by mspgalaxys2lite** [labbots/google-drive-upload#34]
Hi!!! Many thanks for the script. Very much useful.

Is there a way to re-try uploading for failed uploads?
Also, resuming uploading process after the internet connection is resumed?

**Comment by Akianonymus** [comment]
Try and report

https://github.com/Akianonymus/google-drive-upload/blob/fix2/upload.sh

**Comment by mspgalaxys2lite** [comment]
Fantastic mate!!! It works 😀. Thank you very much.
