### ISSUE TITLE
Setup CODACY

### ISSUE THREAD

**Issue by Akianonymus** [labbots/google-drive-upload#37]
Setup codacy to check the code quality of the repo.

Add codacy badge to readme 

https://www.codacy.com

**Comment by labbots** [comment]
Codacy seams to be a paid product and I will look into some open source alternatives.

**Comment by Akianonymus** [comment]
@labbots Codacy is completely free for open source repositories.

**Comment by Akianonymus** [comment]
https://app.codacy.com/login

**Comment by Akianonymus** [comment]
@labbots any update of this ??

I could set it up but i obviously cannot because i don't have write permission to the repo.

Just bumping in case you forgot.

**Comment by labbots** [comment]
@Akianonymus Its in my list of things to do. I want to also write some bats test with mocking for the script and add it as part of actions. I am bit busy at the moment. I will do it when I get some spare time.

**Comment by Akianonymus** [comment]
@labbots what's a bats test ? 🤔

**Comment by labbots** [comment]
Codacy is now setup for the repo @Akianonymus

**Comment by Akianonymus** [comment]
![Screenshot_20200514-033958](https://user-images.githubusercontent.com/32216346/81871100-c91c6080-9594-11ea-8270-4f93e3b5f310.png)

Make sure you disable that code pattern from codacy, otherwise brings a lot of false positives.

https://github.com/remarkjs/remark-lint/issues/78

**Comment by labbots** [comment]
@Akianonymus I have removed the quality pattern for the markdown as suggested but there are still some failures. Hope you could take a look into those too.

**Comment by Akianonymus** [comment]
> @Akianonymus I have removed the quality pattern for the markdown as suggested but there are still some failures. Hope you could take a look into those too.

Can you reset the repo to this commit

https://github.com/labbots/google-drive-upload/commit/74cabb64cbb4d7479d527f5dc387cdd4dc621d0b

I will make pull request to fix those warnings properly and some other stuff.

Also, go to codacy settings, enable as in the screenshot
enable api hook too, follow the instructions

![Screenshot_20200514-113833](https://user-images.githubusercontent.com/32216346/81899114-bd9e5900-95d7-11ea-844c-96833d2f2416.png)

So, codacy can automatically comment to pull requests and will run on every pushed commit.

**Comment by Akianonymus** [comment]
After merging my pr, go to codacy code pattern, and tap on configuration file so it will use the .remarkrc in repository.

**Comment by labbots** [comment]
@Akianonymus I am closing this ticket as it is now complete.

**Comment by Akianonymus** [comment]
Just found out some issues related to codacy, it actually doesn't check shell scripts properly.

We need to enable the all the code patterns manually from the code patterns, which is, pretty much a mess, there are like 200+ shellcheck rules available and obviously we want all of them to trigger.

So, reopening this so you could enable all the code patterns, lot of work though.

Or we could abandon codacy and move to GitHub actions, obviously will need some setup, but can be done.

My thought, option 1 is better.

**Comment by labbots** [comment]
@Akianonymus I have enabled all the code patterns for shell check in Codacy now
