### ISSUE TITLE
Setup github actions for Upload test

### ISSUE THREAD

**Issue by Akianonymus** [labbots/google-drive-upload#39]
Set-up github actions to check for a push or pull request, whether it can upload files or not.

**Comment by labbots** [comment]
I am looking into writing some tests first for the script. I ll look into setting up github actions when the tests are ready.

**Comment by Akianonymus** [comment]
@labbots Beside the test for uploading, i was talking about https://github.com/luizm/action-sh-checker test.

Just found this GitHub actions today, pretty cool.

what do you think ? I can make a pr adding support for this.

**Comment by labbots** [comment]
Seams like a good option @Akianonymus it would be great if you could add the actions.yml for this. I also tried using sonarcloud but it doesnt seam to have bash support. I will try codacy sometime today.

**Comment by labbots** [comment]
@Akianonymus after implementing codacy check. I dont think its necessary to have github actions for PR check. Codacy seams to do PR lint using shellcheck. I will consider setting up github actions once some unit tests are written. For now I believe it is not necessary to set up any actions.

**Comment by Akianonymus** [comment]
> @Akianonymus after implementing codacy check. I dont think its necessary to have github actions for PR check. Codacy seams to do PR lint using shellcheck. I will consider setting up github actions once some unit tests are written. For now I believe it is not necessary to set up any actions.

Yeah, i agree.

**Comment by labbots** [comment]
I am closing this ticket as it is not required at the moment @Akianonymus
