### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MuneebJamil** [labbots/google-drive-upload#4]
upload.sh: line 162: mimetype: command not found

please help me to resolve this issue

![capture](https://user-images.githubusercontent.com/16627059/28494266-661f358c-6f42-11e7-8287-93312536b19d.PNG)

**Comment by labbots** [comment]
@MuneebJamil I am looking into the issue. I will get back to on that shortly.

**Comment by labbots** [comment]
[Pull request](https://github.com/labbots/google-drive-upload/pull/3) from @jimmyppi fixed the issue. Please update the script and see whether that fixes your problem. Thank you.
