### ISSUE TITLE
Feature Request - Support for sync script

### ISSUE THREAD

**Issue by mspgalaxys2lite** [labbots/google-drive-upload#43]
I place all my day-to-day files in work_directory.
I want all the files and folders moved into this directory to be uploaded to google drive.
Is there a way to check if new files are created in this directory, if so, upload them to google drive.
If some files are deleted from the directory, they should not get deleted on google drive.
It is like syncing with google drive but all the files on google drive doesn't get stored on local storage.

**Comment by Akianonymus** [comment]
@mspgalaxys2lite Surely, a nice idea, although it's totally a new script.

Doing it in upload.sh would just mess it.

On another hand, for script to auto-detect new files, it can be done via a background job, which will run continuously, or will run after a interval of time ( again, a reason not to include in existing script ).

The main thing here is running it as a background process, if running just in a terminal shell, then the process will terminate after closing the shell session.

One alternative is to make it a system service ( needs systemd or maybe some alternative ) which will work until the system shutdowns or restart after service has benn started.

Obviously, one other option to not run in background but rather manual trigger by user.

**Comment by mspgalaxys2lite** [comment]
@Akianonymus I understand that it is totally a new script.
Was just thinking of a possibility of running a script at system startup, after which whatever the files we push into it gets uploaded. If the system is shutdown or restarted in the middle of uploading process, the uploading session needs to be saved before shutdown and resume the next time the system is started. As you were saying, making it into a system service should do.
I will myself explore in the direction of getting this thing done. 
Many thanks for the script and considering my issues.

**Comment by mspgalaxys2lite** [comment]
@Akianonymus Btw, I see that -o option helps in overwriting a file. But is there a way to skip uploading file if it is already exists in drive folder? This can save some bandwidth and avoid creation of multiple copies of same file. I see that a new file is being created in the drive folder if we try uploading the same file again (without using -o).

**Comment by Akianonymus** [comment]
@mspgalaxys2lite Well, that's totally possible, please create a new issue.

Currently, script checks the the existing file using the name of the file and the folder ID of the folder, where it is present, for overwriting feature.

Also, i can add a size check too, if the file present on gdrive matches with what present on local drive, would be more sensible maybe for skipping files, any thoughts ?

Sadly, we cannot use md5sum to check file id because while uploading, it changes, otherwise it would've been a perfect implementation.

Size method can fail when the modified file size is exactly same size as the old file.

Note: Size units- Bytes

**Comment by Akianonymus** [comment]
I will try to create a sample script for syncing as soon i get some time.

Drop any more thoughts while we are at it..

**Comment by mspgalaxys2lite** [comment]
@Aki Well, I am not much into CS programming and more into electronics. I
am using ubuntu since many years and just interested in learning bash
scripting and python. You should be knowing better.
Can the "date of creation" of file of be some use?

**Comment by mspgalaxys2lite** [comment]
Sure.

**Comment by labbots** [comment]
@mspgalaxys2lite @Akianonymus I am closing this ticket as skipping duplicate file was implemented as part of #44 bu @Akianonymus.

**Comment by mspgalaxys2lite** [comment]
@labbots ok.

**Comment by Akianonymus** [comment]
@labbots but the main issue of this issue still not resolved, so ...

**Comment by Akianonymus** [comment]
@mspgalaxys2lite Today got some free time and wrote this, it's surely not completed yet, just barebones, but works kinda.

Download the script: `curl -s -o sync_script https://del.dog/raw/pefuwithir`

Start the sync: `bash sync_script folder_you_want_to_sync`

For killing the background session: `bash sync_script folder_you_were_syncing -k`

Change the gupload command according do your use in line 40.

Script checks for new files every 5 secs ( code in line 55 ).

It will run forever until stopped with -k option or terminal session is closed, if you want it to persist even after terminal closing, run the script in a tmux or a screen session ( will see the systemd option after script is completed ).

**Comment by mspgalaxys2lite** [comment]
@Aki not working 😓. should the sync folder name be same as google drive
folder?

**Comment by Akianonymus** [comment]
@mspgalaxys2lite Yeah, you are right, you can change it though, see line 40 after -C, replace "$folder" with your folder name on gdrive

I will soon fix this mess :)

**Comment by mspgalaxys2lite** [comment]
Ok :-)

**Comment by mspgalaxys2lite** [comment]
@Aki Not working even if the folder name is same as google drive folder.
Also, if there is a space in the name of the folder, script doesn't start.

**Comment by Akianonymus** [comment]
@labbots can you open this ? and change title to "Support for sync script"

I almost forgot about this.

**Comment by labbots** [comment]
@Akianonymus I am reopening the issue as requested.

**Comment by mspgalaxys2lite** [comment]
@Aki It looks like "inoticoming" daemon can be used for triggering actions
when changes are made to a directory.

**Comment by Akianonymus** [comment]
@mspgalaxys2lite I will look into soon, been busy :(

Also, i don't want to use external programs, but will see what we can do.

A loop is fine, but obviously takes some cpu resources, if something takes less cpu, then only will think about using it.

Again, this is all after i complete the script.

**Comment by mspgalaxys2lite** [comment]
@Aki ok, np.

**Comment by Akianonymus** [comment]
@mspgalaxys2lite Try and report.

https://github.com/Akianonymus/google-drive-upload/blob/sync/sync.sh

Usage:

`bash sync.sh local_folder -d gdrive_folder`

To kill a background job

`bash sync.sh local_folder -d gdrive_folder -k`

To see background jobs

`bash sync.sh --tasks` ( or use -t )

Full Usage from script:

```shell
Options:

  -i | --interactive - Install script interactively, will ask for all the varibles one by one. Note: This will disregard all arguments given with below flags.
 
  -d | --directory - Gdrive foldername.

  -k | --kill - to kill the background job. To kill, use %s foldername gdrive_folder -k.

  -t | --tasks - see background jobs that were started.\n

  -i | --interval - Amount of time to wait before try to sync again in background.

Default is 3 seconds.

  -l | --logs - To show the logs after starting a job or show log of existing job.

  -h | --help - Display usage instructions. 
```

Make sure you have gupload installed.

**Comment by Akianonymus** [comment]
Also, on another note, after closing the terminal, it will still run in background.

**Comment by labbots** [comment]
@mspgalaxys2lite have you tested the sync script by @Akianonymus? Can this issue be closed?

**Comment by Akianonymus** [comment]
@labbots Whether it's working or not, keep this issue open.

I will make a pr as soon i get some time

Major improvements to scripts, ability to manage sync jobs, etc

**Comment by Akianonymus** [comment]
https://github.com/labbots/google-drive-upload/pull/62

**Comment by mspgalaxys2lite** [comment]
sorry...was busy all these days.. will try and inform as early as possible.

**Comment by Akianonymus** [comment]
@mspgalaxys2lite folders with space in it, it works.

Next, why would you move files in gdrive_folder ? 🤔 it is the remote gdrive folder, doesn't make sense.

Next, please read the readme properly and try to explain your issue, i am not able to understand.

About notifications, will see, never done it.

Last, do below command and try whatever you were trying to, i pushed some other fixes..

```
bash <(curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh) -r Akianonymus/google-drive-upload -B fix
```

**Comment by Akianonymus** [comment]
Also, @mspgalaxy2lite, if you still found any new issue, create a new issue, not continue here.

@labbots you can close this

**Comment by labbots** [comment]
@mspgalaxys2lite I am closing this issue as per @Akianonymus suggestion. Could you please open a new issue if you have any.
