### ISSUE TITLE
Skip uploading file if it exists

### ISSUE THREAD

**Issue by mspgalaxys2lite** [labbots/google-drive-upload#44]
Is there a way to skip uploading file if it already exists in drive folder?

**Comment by Akianonymus** [comment]
any suggestions for short flag name ? 

-s is already taken or i will restructure -s to this feature and skip-dirs to another flag

**Comment by mspgalaxys2lite** [comment]
Its your wish.. Ready to take whatever you give :-)

**Comment by Akianonymus** [comment]
@mspgalaxys2lite Try and report

https://github.com/Akianonymus/google-drive-upload/blob/fix/upload.sh

**Comment by mspgalaxys2lite** [comment]
@Aki It works 😀
