### ISSUE TITLE
Curl error

### ISSUE THREAD

**Issue by MuneebJamil** [labbots/google-drive-upload#5]
thanx for helping me now i am facing new error previous error is removed thanx for that now this error is arrive  i am very thankful to u if u help me to resolve this error when i run this upload name file the text appear   **Go to  and enter  to grant access to this application. Hit enter when done...**  i dont know where to go and grant access to this application and if i enter it as the error come is **curl: (3) <url> malformed**
i am attaching the screenshot of error please help me as soon as possible i will be very thankful to u...
![capture](https://user-images.githubusercontent.com/16627059/28868073-b9afe5b4-7791-11e7-86c8-7725941ddfda.PNG)

**Comment by labbots** [comment]
Looking into this issue. Will get back to you a soon as possible.

**Comment by labbots** [comment]
@MuneebJamil do you have .googledrive.conf created in your user home directory.

**Comment by MuneebJamil** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MuneebJamil** [comment]
It will create automatically

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by labbots** [comment]
Do you have the correct client id and client secret in that config file?

**Comment by MuneebJamil** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MuneebJamil** [comment]
Yes i have tried many ids but same result

**Comment by MuneebJamil** [comment]
When i run the file the msg came go to and access grant to application where to go and grant access

**Comment by kimb** [comment]
ideas:
"2017" doesn't seem like a valid drive folder id?
"/home/pi" is not a file, but a folder?

**Comment by MuneebJamil** [comment]
/home/pi is a path and golder does exist and valid

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
