### ISSUE TITLE
ACCES_TOKEN and REFRESH_TOKEN are not written to custom configuration file

### ISSUE THREAD

**Issue by silviuvulcan** [labbots/google-drive-upload#57]
In case a custom configuration file is used for the first time the ACCES_TOKEN and REFRESH_TOKEN are still written to `~/.googledrive.conf` instead of the file specified with `--config`

**Comment by labbots** [comment]
@silviuvulcan The idea behind `--config` option was to allow override of default config stored in `.googledrive.conf` file. In some specific use case, the user might want to use different config file for upload. This option is not for changing the default config filename.

**Comment by Akianonymus** [comment]
Although he makes sense, if i use a custom config, it should update the custom config, rather than existing one

**Comment by labbots** [comment]
@Akianonymus probably that could be a new feature but its not the existing behaviour of the script. Probably we can add new option for the feature.

**Comment by Akianonymus** [comment]
https://github.com/Akianonymus/google-drive-upload/blob/fix2/upload.sh

> In case a custom configuration file is used for the first time the ACCES_TOKEN and REFRESH_TOKEN are still written to `~/.googledrive.conf` instead of the file specified with `--config`

Try this script

https://github.com/Akianonymus/google-drive-upload/blob/fix2/upload.sh

**Comment by Akianonymus** [comment]
https://github.com/labbots/google-drive-upload/pull/58

this will do it
