### ISSUE TITLE
can gupload download files from gogole drive ?

### ISSUE THREAD

**Issue by juraganfilmmovie** [labbots/google-drive-upload#59]
halo , can gupload download file from google drive also ? i dont see any instruction on how to download files.

**Comment by labbots** [comment]
@juraganfilmmovie This script is just to upload files to google drive. The script does not have option to download files from google drive.

**Comment by labbots** [comment]
@juraganfilmmovie you could use https://github.com/Akianonymus/gdrive-downloader which is specific to downloading files from google drive.

**Comment by juraganfilmmovie** [comment]
@labbots ok thanks bro i'll give it a try
