### ISSUE TITLE
Feature request- HTTP links

### ISSUE THREAD

**Issue by capriciousduck** [labbots/google-drive-upload#61]
I download many files and movies into my server using wget and upload them to my drive using upload. Is it possible for you to implement an auto-upload of files downloaded from HTTP links?

Like `gupload https://speed.hetzner.de/1GB.bin` should download the bin file and upload it automatically instead of I manually uploading the file using `gupload 1GB.bin`

**Comment by labbots** [comment]
@capriciousduck the feature you requested is not part of the scope of the script. You could have a separate script that downloads from source and uploads to google drive using the gupload script.

**Comment by labbots** [comment]
@capriciousduck I am closing this issue as its not within the scope of script.
