### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by capriciousduck** [labbots/google-drive-upload#64]
I get the following error while trying to update the script.

`gupload -u
63: --: Unknown option
Try 63 -h/--help for more information.`

**Comment by Akianonymus** [comment]
> I get the following error while trying to update the script.
> 
> `gupload -u 63: --: Unknown option Try 63 -h/--help for more information.`
```
bash <(curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh)
```
Try this, afterwards, -u flag should as it is meant to be.

**Comment by Akianonymus** [comment]
Will be fixed in after next release

**Comment by capriciousduck** [comment]
I installed the updated script on another server. Still, I get the same error when I execute the update command.

**Comment by Akianonymus** [comment]
@labbots you need to make a new release, then only the fix will work

**Comment by capriciousduck** [comment]
Sorry, what do you mean by a new release? You mean I need to freshly install on a machine?

**Comment by labbots** [comment]
@Akianonymus @capriciousduck I have created a new release v2.6.1.

**Comment by capriciousduck** [comment]
How do I uninstall the script?. The uninstall flag("gupload -U) also doesn't work.

**Comment by labbots** [comment]
@capriciousduck you could install the latest release by running the following command
`bash <(curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh)`

**Comment by Akianonymus** [comment]
@capriciousduck Works here 🤔, strange.

**Comment by Akianonymus** [comment]
This should be closed as the issue is fixed.
