### ISSUE TITLE
Google API credentials not being saved

### ISSUE THREAD

**Issue by Bautista-Baiocchi-lora** [labbots/google-drive-upload#65]
Hello,
I have been using the script to upload files from my ubuntu 18.4 server. Everything worked just fine for the first few days. Now every time I run the script I need to provide my credentials (Client ID, secret, etc).. How can i make these settings be saved as default as before?

**Comment by Bautista-Baiocchi-lora** [comment]
I've concluded that the credentials are being correctly stored in .googledriver.conf...
The error is the following:

/home/bautista/.googledrive.conf: line 6: unexpected EOF while looking for matching `"'
/home/bautista/.googledrive.conf: line 7: syntax error: unexpected end of file

**Comment by Bautista-Baiocchi-lora** [comment]
I was able to fix the error by manually adding a " to the beginning of the second line in .googledrive.conf

Now I get the following error when finishing an upload:
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)

**Comment by labbots** [comment]
@Akianonymus could you please look into this issue?

**Comment by Akianonymus** [comment]
I am not able to reproduce the issue, as said in first comment.

**Comment by Bautista-Baiocchi-lora** [comment]
> I am not able to reproduce the issue, as said in first comment.
I am not sure how to recreate the first but I've commented the fix above. 

As for the curl issue, I think it has to do with Content-Length. It seems to happen on larger files (10MB +) and not on smaller files (~3MB)

Let me know how I can help.

**Comment by Bautista-Baiocchi-lora** [comment]
I am closing this issue and opening a new one to address the Curl error.
