### ISSUE TITLE
[Feature] Uploading gdrive files( urls ) without downloading.

### ISSUE THREAD

**Issue by Akianonymus** [labbots/google-drive-upload#68]
A file uploaded on gdrive, which is accessible i.e either public or shared with the authenticated account, can be copied to any/authenticated account without actually downloading the file.

This can be done with api, using copy parameter.

Folders cannot be achieved directly so need to loop over file ids one by one.

Similar projects: FolderClone, Autorclone, etc.

**Comment by labbots** [comment]
@Akianonymus are you suggesting this only for google drive documents that are shared or files from any links?

**Comment by Akianonymus** [comment]
@labbots Just google drive documents, obviously it won't work on external links without downloading.
