### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by capriciousduck** [labbots/google-drive-upload#70]
Hi, I am using this app to upload my files to google drive. Is there an app to upload to google photos from the command line?

**Comment by labbots** [comment]
@capriciousduck i am currently working on Google photos upload script as different project. It will be available soon.

**Comment by capriciousduck** [comment]
Great!. Let me know, if possible, when it is released.

**Comment by capriciousduck** [comment]
I have seen other google photos command-line apps, and they say that it is not possible to upload to the "High Quality" tier using the API. Do you have any workaround for that?

**Comment by labbots** [comment]
@capriciousduck  google photo upload is not part of this project. It is still in progess and I havent tested what you are asking. I will let you know when the script is available. For now I am closing this ticket as it is not in the scope of this project.
