### ISSUE TITLE
Bash support for MacOS

### ISSUE THREAD

**Issue by norbertschuler** [labbots/google-drive-upload#72]
The installation does not support MacOS (10.15.5) as the bash version available is not supported:

```
$ bash <(curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh)
Bash version lower than 4.x not supported.

$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
```

What can I do to make it work on MacOS?

**Comment by Akianonymus** [comment]
It cannot be updated ? 🤔

**Comment by norbertschuler** [comment]
I am able to install a newer bash with Homebrew and change to the new shell if available:

```
$ bash -version
$ brew reinstall bash
$ bash -version
$ chsh -s /usr/local/bin/bash
```

But then I have a new issues on MacOS:
```
$ gupload test.txt 
Error: Utils file ( ./utils.sh ) not found
```
Background:
I maybe will continue to try to make it work. If I succeed, I will let you know. I wanted to use this tool for our GitHub Action (https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/2485) to upload files to Google Drive as https://github.com/satackey/action-google-drive does not work for me on MacOS due to lack of container support.

**Comment by norbertschuler** [comment]
Of course I could start the script from the folder where `util.sh` is located, but otherwise it does not seem to work on MacOS:
```
$ ~/.google-drive-upload/bin $ gupload ~/test.txt 
```

**Comment by Akianonymus** [comment]
@norbertschuler 
Seems like installation got messed up.

In install script, it adds the utils.sh file path at the top of the script, which enables it to use the file from anywhere.

Can you give me a debug trace when installing from scratch, just run the installation command with -D flag

use 
```
bash <(curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh) -D &> log
```

Upload the log file and send.

**Comment by Akianonymus** [comment]
by the way, you don't need to change default shell to bash, bash is just needed as a binary, just to execute the script.

Default shell can be anything else.

**Comment by norbertschuler** [comment]
> Upload the log file and send.

This is my log file from the installation: [debug.log](https://github.com/labbots/google-drive-upload/files/4823426/debug.log)

**Comment by Akianonymus** [comment]
@norbertschuler Aah, so this was a sed problem.

I have included the fix in my [pull request](https://github.com/labbots/google-drive-upload/pull/71), it should work.

To test now

``` 
bash <(curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh) -r Akianonymus/google-drive-upload -B fix
```

untill my pr is merged and a new release is created.

**Comment by norbertschuler** [comment]
> To test now
> 
> ```
> bash <(curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh) -r Akianonymus/google-drive-upload -B fix
> ```

Thank you. On my local system I could use this, but still get the same error as before, e.g.:
```
$ gupload test.txt
Error: Utils file ( ./utils.sh ) not found
```

I tried to use it on the MacOS machine of GitHub and the installer has problems with usage of `sed` in the old version of the `install.sh` script:
```
sed: -i may not be used with stdin
sed: -i may not be used with stdin
```
and also in the new version of the `install.sh` script (as MacOS has a slightly different version of `sed`):
```
sed: 1: "2a UTILS_FILE="/Users/r ...": command a expects \ followed by text
sed: 1: "2a UTILS_FILE="/Users/r ...": command a expects \ followed by text
```

Also using the new `install.sh` with `bash <(curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/5b5b092a17b01ccc18140be7caf43f9f43b21ae8/install.sh) -r Akianonymus/google-drive-upload -B fix` results into not being able to download the gupload and gsync scripts:
```
$ ls -l .google-drive-upload/bin/
total 48
-rwxr-xr-x  1 norbertschuler  staff      1 24 Jun 14:07 gsync
-rwxr-xr-x  1 norbertschuler  staff      1 24 Jun 14:07 gupload
-rwxr-xr-x  1 norbertschuler  staff  14721 24 Jun 14:07 utils.sh
```

**Comment by Akianonymus** [comment]
@norbertschuler I gave you the wrong command, link was still of this repo.

bash <(curl --compressed -# https://raw.githubusercontent.com/Akianonymus/google-drive-upload/fix/install.sh) -r Akianonymus/google-drive-upload -B fix

try this, most probably a sed bug will arise

will try fix that if that's the case

anyway, on another note, does the upload script works fine ?? it uses sed, just basic features of sed, but still would be helpful if you report, thx.

**Comment by Akianonymus** [comment]
Pushed the fix, doesn't used sed there anymore.

Should be fixed.

use the command in above comment to check.

**Comment by norbertschuler** [comment]
Thank you. Locally it works well for me. Using it with GitHub Actions is different. Currently GitHub is blocking itself not allowing the curl command to fetch the latest SHA for the script to work correctly (took me some time to understand this was the reason why the `gupload` and `gsync` scripts could not be downloaded afterwards):
```
curl --compressed -s https://api.github.com/repos/Akianonymus/google-drive-upload/commits/fix
{"message":"API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```
If this works again I would be able to check if using this script in GitHub Actions could also be usable. As I cannot access the build system, I will have to fill all the values within the config file `.googledrive.conf` from secrets I will add to our repository, but I am not sure how long the ACCESS_TOKEN and REFRESH_TOKEN are valid - so maybe this is no script to be used for a CI pipeline.

**Comment by Akianonymus** [comment]
@norbertschuler Ooh, well, that can be fixed, to fetch the latest sha.

Also, refresh token never expires

and access token is automatically updated if it's expired, it's implemented in the script.

So, yes, it can be easily used in ci pipelines given i fix the sha fetching method.

**Comment by Akianonymus** [comment]
Well, funny fact it, previously it was not using api to fetch the sha, so avoiding that issue

I did this as obviously, api is a cleaner way, just have to revert now.

**Comment by norbertschuler** [comment]
> Well, funny fact it, previously it was not using api to fetch the sha, so avoiding that issue
> 
> I did this as obviously, api is a cleaner way, just have to revert now. 

Well, if you do I will continue trying to use it :-)

**Comment by Akianonymus** [comment]
@norbertschuler Just did :)

https://github.com/labbots/google-drive-upload/commit/6c1ece2df9c29d8674193e45a1bb58edcf080fd5

Check in github actions, if it works.
