### ISSUE TITLE
automatically retry on failed files

### ISSUE THREAD

**Issue by icy** [labbots/google-drive-upload#84]
Hi there,

is there any way for the script to retry automatically on failed files? Now I have to run the script again and again, which is not very convenient on remote session.

Thanks

**Comment by Akianonymus** [comment]
@icy use gsync

`gsync foldername some_arguments --foreground`

as it's a sync job it will repeat for failed files, and with --foreground flag, it will run foreground like as gupload command.

**Comment by Akianonymus** [comment]
Implemented retry for file uploads

https://github.com/labbots/google-drive-upload/pull/87

# Todo: Normal and parallel folder uploading

**Comment by labbots** [comment]
@icy This option is now available with 2.7.4 release

**Comment by icy** [comment]
@labbots awesome, thx a lot for the quick support :)

**Comment by labbots** [comment]
Great contribution from @Akianonymus
