### ISSUE TITLE
issue access_token

### ISSUE THREAD

**Issue by jackly20** [labbots/google-drive-upload#86]
I have created refesh_token and using command `./google-oauth2.sh refresh update` for creating access_token and it has updated content key ACCESS_TOKEN in file ~/.googledrive.conf but look like it doesn't work,  time expired of access_token still is initial access_token, not access_token I have created above. Please check to help me issue

**Comment by Akianonymus** [comment]
Fixed in https://github.com/labbots/google-drive-upload/pull/87

**Comment by labbots** [comment]
@jackly20  could you please try the new 2.7.4 release
