### ISSUE TITLE
Refresh token not stored in .googledrive.conf in version 2.7.3?

### ISSUE THREAD

**Issue by norbertschuler** [labbots/google-drive-upload#88]
I am currently using version 2.7 which stores the REFRESH_TOKEN in the file `.googledrive.conf`. I tested to change to the new version 2.7.3, but this version does not seem to store the REFRESH_TOKEN in `.googledrive.conf` and instead ask me for a refresh token on every run of `gupload`. I did a completely new install of version 2.7.3 and not an update.

Is that a wanted behavior or a bug - I need to be able to run the script without user interaction.

**Comment by labbots** [comment]
@norbertschuler could you please try the new 2.7.4 release

**Comment by Akianonymus** [comment]
This is indeed a valid bug i missed because I don't usually do new setups.

Pushed the fix, pr here

https://github.com/labbots/google-drive-upload/pull/89

**Comment by Akianonymus** [comment]
i think this can be closed now.

**Comment by norbertschuler** [comment]
> @norbertschuler could you please try the new 2.7.4 release

Can't do for the next time. Please just go on if you think it's fixed.
