### ISSUE TITLE
Is there support for config

### ISSUE THREAD

**Issue by ElytrA8** [labbots/google-drive-upload#90]
I want to run workflows which upload to gdrive using config coz I can't access cli

**Comment by labbots** [comment]
@ElytrA8 The script has option to pass the .googledrive.conf file as config parameter. You could use -z | --config option to pass different configurations.

**Comment by ElytrA8** [comment]
Where should I get sample config
It would be great help thanks

**Comment by ElytrA8** [comment]
Great work btw thanks for it

**Comment by labbots** [comment]
You could do a initial setup on your local machine. This would create a .googledrive.conf file in the home directory. This step is required as you need to configure the access token and refresh tokens that you received from google developer console with access to google drive API.

**Comment by Akianonymus** [comment]
@ElytrA8 see https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/.github/workflows/macos_build_ios.yml#L58 and how to do without cli access, obviously you should have those credentials beforehand.

On side note, this should be added in README as a little to handle authentication in case of CIs/non-accessible terminal.

**Comment by ElytrA8** [comment]
Thank you so much
Really Appreciate your work
