### ISSUE TITLE
New installation of 3.1.1 fails due to missing refresh_token

### ISSUE THREAD

**Issue by norbertschuler** [labbots/google-drive-upload#95]
After installing with curl when trying to upload a file for the first time, I have no refresh_token, so I just skipped that input field. The gupload script then asks to get a token from an url, but it does not wait anymore for input, but fails with the following error:
```
$ gupload test.txt 
------------------------------------------------------[ Starting script ]-------------------------------------------------------
---------------------------------------------------[ Checking credentials.. ]---------------------------------------------------
If you have a refresh token generated, then type the token, else leave blank and press return key..

Refresh Token: 

Visit the below URL, tap on allow and then enter the code obtained:
https://accounts.google.com/o/oauth2/auth?client_id=XXX&redirect_uri=urn:ietf:wg:oauth:2.0:oob&scope=https://www.googleapis.com/auth/drive&response_type=code&prompt=consent
========================================[ Error: Something went wrong, printing error. ]========================================
{
  "error": "invalid_request",
  "error_description": "Missing required parameter: refresh_token"
}
```
I was using version v2.7 and tried to upgrade to v.3.1.1 on MacOS.

**Comment by Akianonymus** [comment]
> After installing with curl when trying to upload a file for the first time, I have no refresh_token, so I just skipped that input field. The gupload script then asks to get a token from an url, but it does not wait anymore for input, but fails with the following error:
> 
> ```
> $ gupload test.txt 
> ------------------------------------------------------[ Starting script ]-------------------------------------------------------
> ---------------------------------------------------[ Checking credentials.. ]---------------------------------------------------
> If you have a refresh token generated, then type the token, else leave blank and press return key..
> 
> Refresh Token: 
> 
> Visit the below URL, tap on allow and then enter the code obtained:
> https://accounts.google.com/o/oauth2/auth?client_id=XXX&redirect_uri=urn:ietf:wg:oauth:2.0:oob&scope=https://www.googleapis.com/auth/drive&response_type=code&prompt=consent
> ========================================[ Error: Something went wrong, printing error. ]========================================
> {
>   "error": "invalid_request",
>   "error_description": "Missing required parameter: refresh_token"
> }
> ```
> 
> I was using version v2.7 and tried to upgrade to v.3.1.1 on MacOS.

It's not waiting for the code ? right ?

I pushed some fixes, please try again.

**Comment by Akianonymus** [comment]
To try, use this command

```
curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh | sh -s -- -B tmp
```

**Comment by norbertschuler** [comment]
> To try, use this command
> 
> ```
> curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh | sh -s -- -B tmp
> ```

Works for me.

**Comment by Akianonymus** [comment]
https://github.com/labbots/google-drive-upload/releases/tag/v3.1.2

A new release has been created.

Also, on sidenote, you don't need install gnu sed for scripts to work.

I have made changes which works find with macos primitive sed.
